# Generated by Django 5.2.16 on 2026-07-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('bar_id', models.CharField(max_length=36)),
                ('nom', models.CharField(max_length=120)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'credit_creances_client',
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('bar_id', 'nom'), name='un_client_par_nom_et_bar')],
            },
        ),
        migrations.CreateModel(
            name='CreditModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=36)),
                ('addition_id', models.CharField(max_length=36, unique=True)),
                ('montant', models.PositiveIntegerField()),
                ('statut', models.CharField(max_length=16)),
                ('ne_le', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='credit_creances.clientmodel')),
            ],
            options={
                'db_table': 'credit_creances_credit',
                'ordering': ['ne_le'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=36)),
                ('montant', models.PositiveIntegerField()),
                ('auteur_id', models.CharField(max_length=36)),
                ('horodatage', models.DateTimeField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='credit_creances.creditmodel')),
            ],
            options={
                'db_table': 'credit_creances_remboursement',
                'ordering': ['horodatage'],
            },
        ),
        migrations.AddIndex(
            model_name='creditmodel',
            index=models.Index(fields=['client', 'statut'], name='credit_crea_client__31090d_idx'),
        ),
    ]
