# Generated by Django 5.2.16 on 2026-07-24 14:17

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=60)),
                ('auteur_id', models.CharField(max_length=36)),
                ('donnees', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('horodatage_saisie', models.DateTimeField()),
                ('horodatage_reception', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service_ventes_mouvement',
                'ordering': ['horodatage_reception'],
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('bar_id', models.CharField(max_length=36)),
                ('responsable_id', models.CharField(max_length=36)),
                ('responsable_capacite', models.CharField(max_length=20)),
                ('fond_de_caisse', models.PositiveIntegerField()),
                ('statut', models.CharField(max_length=20)),
                ('ouvert_le', models.DateTimeField()),
                ('clos_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_ventes_service',
            },
        ),
    ]
