# Generated by Django 5.2.16 on 2026-07-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('produit_id', models.CharField(max_length=36)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('montant_total', models.PositiveIntegerField()),
                ('forme_paiement', models.CharField(max_length=20)),
                ('horodatage', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='service_ventes.servicemodel')),
            ],
            options={
                'db_table': 'service_ventes_vente',
                'ordering': ['horodatage'],
            },
        ),
    ]
