# Generated by Django 5.2.16 on 2026-07-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_ventes', '0002_ventemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('table_numero', models.PositiveIntegerField()),
                ('statut', models.CharField(max_length=20)),
                ('ouvert_le', models.DateTimeField()),
                ('ferme_le', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additions', to='service_ventes.servicemodel')),
            ],
            options={
                'db_table': 'service_ventes_addition',
                'ordering': ['ouvert_le'],
            },
        ),
    ]
