# Generated by Django 5.2.16 on 2026-07-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_ventes', '0003_additionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventemodel',
            name='addition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='service_ventes.additionmodel'),
        ),
    ]
