# Generated by Django 5.2.16 on 2026-07-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_ventes', '0005_retirer_mouvementmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField()),
                ('forme_paiement', models.CharField(max_length=20)),
                ('horodatage', models.DateTimeField()),
                ('addition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='service_ventes.additionmodel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='service_ventes.servicemodel')),
            ],
            options={
                'db_table': 'service_ventes_paiement',
                'ordering': ['horodatage'],
            },
        ),
    ]
