# Generated by Django 5.2.16 on 2026-07-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErreurTechnique',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('methode', models.CharField(max_length=10)),
                ('chemin', models.CharField(max_length=255)),
                ('statut', models.PositiveSmallIntegerField()),
                ('auteur_id', models.CharField(blank=True, default='', max_length=36)),
                ('exception', models.CharField(blank=True, default='', max_length=255)),
                ('trace', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'observabilite_erreur',
                'ordering': ['-id'],
            },
        ),
    ]
