# Generated by Django 5.2.16 on 2026-07-28 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bars_possedes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gouvernance_bar',
            },
        ),
        migrations.CreateModel(
            name='CompteModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('capacites', models.JSONField(default=list)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='gouvernance.barmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_gouvernance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gouvernance_compte',
            },
        ),
        migrations.AddConstraint(
            model_name='barmodel',
            constraint=models.UniqueConstraint(fields=('proprietaire', 'nom'), name='un_bar_par_nom_et_proprietaire'),
        ),
        migrations.AddConstraint(
            model_name='comptemodel',
            constraint=models.UniqueConstraint(fields=('bar', 'user'), name='un_compte_par_user_et_bar'),
        ),
    ]
