# Generated by Django 5.2.16 on 2026-07-29 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesPlateformeModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('administrateur_id', models.CharField(max_length=36)),
                ('bar_id', models.CharField(max_length=36)),
                ('operation', models.CharField(max_length=120)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gouvernance_acces_plateforme',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['bar_id', '-horodatage'], name='acces_par_bar_et_date')],
            },
        ),
        migrations.CreateModel(
            name='AdministrateurPlateformeModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('capacites', models.JSONField(default=list)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administration_plateforme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gouvernance_administrateur_plateforme',
            },
        ),
    ]
