# Generated by Django 5.2.16 on 2026-07-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('bar_id', models.CharField(max_length=36)),
                ('nom', models.CharField(max_length=120)),
                ('prix', models.PositiveIntegerField()),
                ('en_vente', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogue_produit',
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('bar_id', 'nom'), name='un_produit_par_nom_et_bar')],
            },
        ),
    ]
