/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as BarsRouteImport } from './routes/bars'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ClotureRouteImport } from './routes/cloture'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CreancesRouteImport } from './routes/creances'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as InventaireRouteImport } from './routes/inventaire'
import { Route as JournalAccesRouteImport } from './routes/journal-acces'
import { Route as RecetteRouteImport } from './routes/recette'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as VenteRouteImport } from './routes/vente'
import { Route as CreancesClientIdRouteImport } from './routes/creances.$clientId'
import { Route as TablesAidRouteImport } from './routes/tables.$aid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const BarsRoute = BarsRouteImport.update({
  id: '/bars',
  path: '/bars',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ClotureRoute = ClotureRouteImport.update({
  id: '/cloture',
  path: '/cloture',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CreancesRoute = CreancesRouteImport.update({
  id: '/creances',
  path: '/creances',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const InventaireRoute = InventaireRouteImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalAccesRoute = JournalAccesRouteImport.update({
  id: '/journal-acces',
  path: '/journal-acces',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetteRoute = RecetteRouteImport.update({
  id: '/recette',
  path: '/recette',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const VenteRoute = VenteRouteImport.update({
  id: '/vente',
  path: '/vente',
  getParentRoute: () => rootRouteImport,
} as any)
const CreancesClientIdRoute = CreancesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CreancesRoute,
} as any)
const TablesAidRoute = TablesAidRouteImport.update({
  id: '/$aid',
  path: '/$aid',
  getParentRoute: () => TablesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/bars': typeof BarsRoute
  '/catalogue': typeof CatalogueRoute
  '/cloture': typeof ClotureRoute
  '/connexion': typeof ConnexionRoute
  '/creances': typeof CreancesRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/inventaire': typeof InventaireRoute
  '/journal-acces': typeof JournalAccesRoute
  '/recette': typeof RecetteRoute
  '/reglages': typeof ReglagesRoute
  '/tables': typeof TablesRouteWithChildren
  '/vente': typeof VenteRoute
  '/creances/$clientId': typeof CreancesClientIdRoute
  '/tables/$aid': typeof TablesAidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/bars': typeof BarsRoute
  '/catalogue': typeof CatalogueRoute
  '/cloture': typeof ClotureRoute
  '/connexion': typeof ConnexionRoute
  '/creances': typeof CreancesRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/inventaire': typeof InventaireRoute
  '/journal-acces': typeof JournalAccesRoute
  '/recette': typeof RecetteRoute
  '/reglages': typeof ReglagesRoute
  '/tables': typeof TablesRouteWithChildren
  '/vente': typeof VenteRoute
  '/creances/$clientId': typeof CreancesClientIdRoute
  '/tables/$aid': typeof TablesAidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/bars': typeof BarsRoute
  '/catalogue': typeof CatalogueRoute
  '/cloture': typeof ClotureRoute
  '/connexion': typeof ConnexionRoute
  '/creances': typeof CreancesRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/inventaire': typeof InventaireRoute
  '/journal-acces': typeof JournalAccesRoute
  '/recette': typeof RecetteRoute
  '/reglages': typeof ReglagesRoute
  '/tables': typeof TablesRouteWithChildren
  '/vente': typeof VenteRoute
  '/creances/$clientId': typeof CreancesClientIdRoute
  '/tables/$aid': typeof TablesAidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accueil'
    | '/bars'
    | '/catalogue'
    | '/cloture'
    | '/connexion'
    | '/creances'
    | '/equipe'
    | '/inventaire'
    | '/journal-acces'
    | '/recette'
    | '/reglages'
    | '/tables'
    | '/vente'
    | '/creances/$clientId'
    | '/tables/$aid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accueil'
    | '/bars'
    | '/catalogue'
    | '/cloture'
    | '/connexion'
    | '/creances'
    | '/equipe'
    | '/inventaire'
    | '/journal-acces'
    | '/recette'
    | '/reglages'
    | '/tables'
    | '/vente'
    | '/creances/$clientId'
    | '/tables/$aid'
  id:
    | '__root__'
    | '/'
    | '/accueil'
    | '/bars'
    | '/catalogue'
    | '/cloture'
    | '/connexion'
    | '/creances'
    | '/equipe'
    | '/inventaire'
    | '/journal-acces'
    | '/recette'
    | '/reglages'
    | '/tables'
    | '/vente'
    | '/creances/$clientId'
    | '/tables/$aid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccueilRoute: typeof AccueilRoute
  BarsRoute: typeof BarsRoute
  CatalogueRoute: typeof CatalogueRoute
  ClotureRoute: typeof ClotureRoute
  ConnexionRoute: typeof ConnexionRoute
  CreancesRoute: typeof CreancesRouteWithChildren
  EquipeRoute: typeof EquipeRoute
  InventaireRoute: typeof InventaireRoute
  JournalAccesRoute: typeof JournalAccesRoute
  RecetteRoute: typeof RecetteRoute
  ReglagesRoute: typeof ReglagesRoute
  TablesRoute: typeof TablesRouteWithChildren
  VenteRoute: typeof VenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bars': {
      id: '/bars'
      path: '/bars'
      fullPath: '/bars'
      preLoaderRoute: typeof BarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloture': {
      id: '/cloture'
      path: '/cloture'
      fullPath: '/cloture'
      preLoaderRoute: typeof ClotureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creances': {
      id: '/creances'
      path: '/creances'
      fullPath: '/creances'
      preLoaderRoute: typeof CreancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventaire': {
      id: '/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof InventaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-acces': {
      id: '/journal-acces'
      path: '/journal-acces'
      fullPath: '/journal-acces'
      preLoaderRoute: typeof JournalAccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recette': {
      id: '/recette'
      path: '/recette'
      fullPath: '/recette'
      preLoaderRoute: typeof RecetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vente': {
      id: '/vente'
      path: '/vente'
      fullPath: '/vente'
      preLoaderRoute: typeof VenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creances/$clientId': {
      id: '/creances/$clientId'
      path: '/$clientId'
      fullPath: '/creances/$clientId'
      preLoaderRoute: typeof CreancesClientIdRouteImport
      parentRoute: typeof CreancesRoute
    }
    '/tables/$aid': {
      id: '/tables/$aid'
      path: '/$aid'
      fullPath: '/tables/$aid'
      preLoaderRoute: typeof TablesAidRouteImport
      parentRoute: typeof TablesRoute
    }
  }
}

interface CreancesRouteChildren {
  CreancesClientIdRoute: typeof CreancesClientIdRoute
}

const CreancesRouteChildren: CreancesRouteChildren = {
  CreancesClientIdRoute: CreancesClientIdRoute,
}

const CreancesRouteWithChildren = CreancesRoute._addFileChildren(
  CreancesRouteChildren,
)

interface TablesRouteChildren {
  TablesAidRoute: typeof TablesAidRoute
}

const TablesRouteChildren: TablesRouteChildren = {
  TablesAidRoute: TablesAidRoute,
}

const TablesRouteWithChildren =
  TablesRoute._addFileChildren(TablesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccueilRoute: AccueilRoute,
  BarsRoute: BarsRoute,
  CatalogueRoute: CatalogueRoute,
  ClotureRoute: ClotureRoute,
  ConnexionRoute: ConnexionRoute,
  CreancesRoute: CreancesRouteWithChildren,
  EquipeRoute: EquipeRoute,
  InventaireRoute: InventaireRoute,
  JournalAccesRoute: JournalAccesRoute,
  RecetteRoute: RecetteRoute,
  ReglagesRoute: ReglagesRoute,
  TablesRoute: TablesRouteWithChildren,
  VenteRoute: VenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
