# Generated by Django 5.2.16 on 2026-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequeteIdempotente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('porteur', models.CharField(max_length=64)),
                ('cle', models.CharField(max_length=200)),
                ('empreinte', models.CharField(max_length=64)),
                ('statut', models.CharField(default='en_cours', max_length=10)),
                ('code_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('corps', models.BinaryField(blank=True, null=True)),
                ('type_contenu', models.CharField(blank=True, default='', max_length=100)),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'idempotence_requete',
                'constraints': [models.UniqueConstraint(fields=('porteur', 'cle'), name='une_cle_par_porteur')],
            },
        ),
    ]
